export const CURRENCIES = [
  {
    code: 'BTC',
    name: 'Bitcoin',
    logo: 'https://picsum.photos/id/236/200/300',
    priceUsd: null,
    changePercent24Hr: null,
  },
  {
    code: 'ETH',
    name: 'Ethereum',
    logo: 'https://picsum.photos/id/238/200/300',
    priceUsd: null,
    changePercent24Hr: null,
  },
  {
    code: 'SOL',
    name: 'Solana',
    logo: 'https://picsum.photos/id/239/200/300',
    priceUsd: null,
    changePercent24Hr: null,
  },
  {
    code: 'BNB',
    name: 'Binance Coin',
    logo: 'https://picsum.photos/id/240/200/300',
    priceUsd: null,
    changePercent24Hr: null,
  },
  {
    code: 'ADA',
    name: 'Cardano',
    logo: 'https://picsum.photos/id/241/200/300',
    priceUsd: null,
    changePercent24Hr: null,
  },
  {
    code: 'XRP',
    name: 'XRP',
    logo: 'https://picsum.photos/id/242/200/300',
    priceUsd: null,
    changePercent24Hr: null,
  },
  {
    code: 'DOGE',
    name: 'Dogecoin',
    logo: 'https://picsum.photos/id/243/200/300',
    priceUsd: null,
    changePercent24Hr: null,
  },
  {
    code: 'DOT',
    name: 'Polkadot',
    logo: 'https://picsum.photos/id/244/200/300',
    priceUsd: null,
    changePercent24Hr: null,
  },
  {
    code: 'AVAX',
    name: 'Avalanche',
    logo: 'https://picsum.photos/id/100/200/300',
    priceUsd: null,
    changePercent24Hr: null,
  },
  {
    code: 'MATIC',
    name: 'Polygon',
    logo: 'https://picsum.photos/id/101/200/300',
    priceUsd: null,
    changePercent24Hr: null,
  },
  {
    code: 'LTC',
    name: 'Litecoin',
    logo: 'https://picsum.photos/id/247/200/300',
    priceUsd: null,
    changePercent24Hr: null,
  },
  {
    code: 'TRX',
    name: 'TRON',
    logo: 'https://picsum.photos/id/248/200/300',
    priceUsd: null,
    changePercent24Hr: null,
  },
  {
    code: 'LINK',
    name: 'Chainlink',
    logo: 'https://picsum.photos/id/249/200/300',
    priceUsd: null,
    changePercent24Hr: null,
  },
  {
    code: 'UNI',
    name: 'Uniswap',
    logo: 'https://picsum.photos/id/250/200/300',
    priceUsd: null,
    changePercent24Hr: null,
  },
  {
    code: 'ATOM',
    name: 'Cosmos',
    logo: 'https://picsum.photos/id/251/200/300',
    priceUsd: null,
    changePercent24Hr: null,
  },
]
